'use client';

import React, { useEffect, useState } from 'react';
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs';
import { AntoniaAppSuggestion } from '@/lib/types';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Loader2, CheckCircle, Lightbulb, Zap, Bug } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

export default function AdminSuggestionsPage() {
    const [suggestions, setSuggestions] = useState<AntoniaAppSuggestion[]>([]);
    const [loading, setLoading] = useState(true);
    const supabase = createClientComponentClient();
    const { toast } = useToast();

    useEffect(() => {
        async function load() {
            // Security: RLS should handle this, but UI can also redirect if not admin
            const { data, error } = await supabase
                .from('antonia_app_suggestions')
                .select('*')
                .order('created_at', { ascending: false });

            if (data) setSuggestions(data);
            setLoading(false);
        }
        load();
    }, [supabase]);

    const handleMarkRead = async (id: string) => {
        const { error } = await supabase
            .from('antonia_app_suggestions')
            .update({ is_read: true })
            .eq('id', id);

        if (!error) {
            setSuggestions(suggestions.map(s => s.id === id ? { ...s, isRead: true } : s));
            toast({ title: 'Marked as Read' });
        }
    };

    const getIcon = (type: string) => {
        switch (type) {
            case 'feature': return <Lightbulb className="w-5 h-5 text-yellow-500" />;
            case 'optimization': return <Zap className="w-5 h-5 text-blue-500" />;
            case 'bug': return <Bug className="w-5 h-5 text-red-500" />;
            default: return <Lightbulb className="w-5 h-5" />;
        }
    };

    if (loading) return <div className="p-10 flex justify-center"><Loader2 className="animate-spin h-8 w-8" /></div>;

    return (
        <div className="container mx-auto p-6 max-w-5xl space-y-8">
            <div>
                <h1 className="text-3xl font-bold">ANTONIA's Brain</h1>
                <p className="text-muted-foreground">Self-improvement suggestions generated by the AI agent.</p>
            </div>

            <div className="grid gap-4">
                {suggestions.length === 0 ? (
                    <Card><CardContent className="py-8 text-center text-muted-foreground">No suggestions yet. The agent is happy.</CardContent></Card>
                ) : (
                    suggestions.map(s => (
                        <Card key={s.id} className={`transition-opacity ${s.isRead ? 'opacity-60 bg-secondary/10' : ''}`}>
                            <CardHeader className="flex flex-row items-center gap-4 space-y-0">
                                <div className="p-2 bg-secondary rounded-full">
                                    {getIcon(s.suggestionType)}
                                </div>
                                <div className="flex-1">
                                    <div className="flex justify-between">
                                        <CardTitle className="text-lg">{s.description}</CardTitle>
                                        <Badge variant={s.isRead ? 'outline' : 'default'}>
                                            {s.suggestionType.toUpperCase()}
                                        </Badge>
                                    </div>
                                    <CardDescription className="mt-1">
                                        Context: {s.context || 'General observation'}
                                    </CardDescription>
                                </div>
                            </CardHeader>
                            <CardContent className="flex justify-end gap-2">
                                {!s.isRead && (
                                    <Button size="sm" variant="ghost" onClick={() => handleMarkRead(s.id)}>
                                        <CheckCircle className="w-4 h-4 mr-2" /> Mark as Read
                                    </Button>
                                )}
                            </CardContent>
                        </Card>
                    ))
                )}
            </div>
        </div>
    );
}
