'use client';
import {useCallback,useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {usePathname,useRouter,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {Activity,ArrowLeft,ArrowRight,CalendarDays,CheckCircle2,Coins,Download,RefreshCw,Search,Users,AlertCircle,ChevronRight} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,XAxis,YAxis,Tooltip} from 'recharts';
import {Button} from '@/components/ui/button';
import {Card,CardContent,CardHeader,CardTitle as CardTitleBase} from '@/components/ui/card';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Skeleton} from '@/components/ui/skeleton';
import {ChartContainer,ChartTooltipContent} from '@/components/ui/chart';
import {Badge} from '@/components/ui/badge';
import {USAGE_MODULES,usageReportCsv,type AdminUsageReport,type CommercialCounts} from '@/lib/admin/usage';
import {dayInZone,lastDaysInZone,shiftDay} from '@/lib/admin/chile-time';
import {cn} from '@/lib/utils';

const n=(value:number|null|undefined)=>value===null||value===undefined?'—':value.toLocaleString('es-CL');
const date=(value:string)=>new Date(value+'T12:00:00Z').toLocaleDateString('es-CL',{day:'numeric',month:'short',timeZone:'UTC'}).replace('.','');
const time=(value:string|null)=>value?new Date(value).toLocaleString('es-CL',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'America/Santiago'}).replace('.',''):'Sin uso registrado';
const chartConfig={active:{label:'Personas activas',color:'hsl(var(--chart-1))'},credits:{label:'Créditos del cupo diario',color:'hsl(var(--chart-2))'}};
const commercialLabels:Array<{key:keyof CommercialCounts;label:string}>=[{key:'saved',label:'Contactos guardados'},
  {key:'researchCompleted',label:'Investigaciones terminadas'},{key:'drafts',label:'Borradores preparados'},{key:'contacted',label:'Contactos con envío registrado'},
  {key:'humanReplies',label:'Respuestas humanas clasificadas'},{key:'interested',label:'Contactos con interés registrado'},
  {key:'meetingRequested',label:'Solicitudes de reunión'},{key:'meetingRegistered',label:'Reuniones registradas con fecha'},
  {key:'meetingCompleted',label:'Reuniones marcadas como realizadas'},{key:'qualified',label:'Calificados en CRM'},
  {key:'linkedinConfirmed',label:'Envíos LinkedIn confirmados'},
  {key:'negotiating',label:'En negociación en CRM'},{key:'won',label:'Cierres registrados como ganados'},{key:'lost',label:'Cierres registrados como perdidos'}];
const diagnosticLabels={technical:'Revisión técnica',setup:'Configuración',pending:'Trabajo pendiente',protection:'Protección',strategy:'Revisión comercial',observing:'En observación'};
function CardTitle({children,className}:{children:ReactNode;className?:string}){return <CardTitleBase className={className}><h2>{children}</h2></CardTitleBase>;}
function Loading(){return <div className="space-y-5" aria-busy="true" aria-label="Cargando uso y resultados"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{Array.from({length:4},(_,i)=><Skeleton key={i} className="h-28 rounded-2xl"/>)}</div><Skeleton className="h-80 rounded-2xl"/><Skeleton className="h-72 rounded-2xl"/></div>;}
function Metric({label,value,detail,icon:Icon}:{label:string;value:number|null;detail:string;icon:typeof Users}){return <Card className="border-border/60"><CardContent className="p-4 sm:p-5"><div className="flex items-center justify-between gap-2"><p className="text-sm text-muted-foreground">{label}</p><Icon className="h-4 w-4 text-primary" aria-hidden="true"/></div><p className="mt-3 text-3xl font-semibold tabular-nums tracking-tight">{n(value)}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></CardContent></Card>;}

export function UsageDashboard(){
  const pathname=usePathname(),router=useRouter(),params=useSearchParams();
  const initial=lastDaysInZone(30);
  const [from,setFrom]=useState(params.get('from')||initial.from),[to,setTo]=useState(params.get('to')||initial.to);
  const [org,setOrg]=useState(params.get('organizationId')||''),[group,setGroup]=useState(params.get('groupId')||''),[person,setPerson]=useState(params.get('userId')||'');
  const [view,setView]=useState(['summary','people','commercial','history'].includes(params.get('view')||'')?params.get('view')!:'summary');
  const [data,setData]=useState<AdminUsageReport|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [query,setQuery]=useState(''),[sort,setSort]=useState('activity'),[horizon,setHorizon]=useState(params.get('horizon')||'14');
  const [chart,setChart]=useState<'active'|'credits'>('active'),[selectedDay,setSelectedDay]=useState<string|null>(null),[exportError,setExportError]=useState('');
  const sequence=useRef(0),activeController=useRef<AbortController|null>(null),lastScope=useRef('');
  const dayOpener=useRef<HTMLElement|null>(null);
  const heading=useRef<HTMLHeadingElement|null>(null),focusedPerson=useRef('');
  const load=useCallback(async()=>{
    activeController.current?.abort();const controller=new AbortController();activeController.current=controller;const id=++sequence.current;
    setLoading(true);setError('');
    const scope=`${org}:${group}:${person}:${from}:${to}:${horizon}`;if(lastScope.current!==scope){setData(null);setSelectedDay(null);lastScope.current=scope;}
    try{
      const search=new URLSearchParams({from,to,horizon});if(org)search.set('organizationId',org);if(group)search.set('groupId',group);if(person)search.set('userId',person);
      const response=await fetch('/api/dashboard/admin/usage?'+search,{cache:'no-store',signal:controller.signal});
      const body=await response.json();
      if(id!==sequence.current||controller.signal.aborted)return;
      if(!response.ok){if([401,403].includes(response.status)){setData(null);setSelectedDay(null);}throw Error(body.error||'No pudimos actualizar el informe.');}
      if(id===sequence.current&&!controller.signal.aborted)setData(body);
    }catch(problem){if(!controller.signal.aborted&&id===sequence.current)setError(problem instanceof Error?problem.message:'No pudimos actualizar el informe.');}
    finally{if(id===sequence.current&&!controller.signal.aborted)setLoading(false);}
  },[from,to,org,group,person,horizon]);
  useEffect(()=>{void load();return()=>activeController.current?.abort();},[load]);
  useEffect(()=>{
    const search=new URLSearchParams({from,to,view,horizon});if(org)search.set('organizationId',org);if(group)search.set('groupId',group);if(person)search.set('userId',person);
    router.replace(pathname+'?'+search,{scroll:false});
  },[from,to,view,horizon,org,group,person,router,pathname]);
  const effectiveOrg=org||data?.selectedOrganizationId||'';
  const currentPerson=data?.people.find(p=>p.id===person&&p.organizationId===effectiveOrg);
  useEffect(()=>{const key=person?`${effectiveOrg}:${person}`:'';if(currentPerson&&key!==focusedPerson.current){focusedPerson.current=key;heading.current?.focus();}if(!person)focusedPerson.current='';},[currentPerson,effectiveOrg,person]);
  const visiblePeople=useMemo(()=>{
    const rows=(data?.people||[]).filter(p=>`${p.name} ${p.email}`.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es')));
    return [...rows].sort((a,b)=>sort==='credits'?(b.credits??-1)-(a.credits??-1):sort==='days'?b.activeDays-a.activeDays:sort==='pending'?b.pending-a.pending:(b.lastAt||'').localeCompare(a.lastAt||'')||a.name.localeCompare(b.name,'es'));
  },[data,query,sort]);
  const day=data?.daily.find(d=>d.day===selectedDay);
  const openPerson=(organizationId:string,userId:string)=>{setOrg(organizationId);setPerson(userId);setView('summary');setSelectedDay(null);setQuery('');};
  const shortcuts=(days:number)=>{const range=days===0?{from:shiftDay(dayInZone(new Date()),-1),to:shiftDay(dayInZone(new Date()),-1)}:lastDaysInZone(days);setFrom(range.from);setTo(range.to);setSelectedDay(null);};
  const exportCsv=()=>{if(!data)return;setExportError('');try{const url=URL.createObjectURL(new Blob([usageReportCsv(data)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`uso-resultados-${from}-${to}.csv`;a.click();URL.revokeObjectURL(url);}catch{setExportError('No pudimos descargar el resumen. Inténtalo de nuevo.');}};
  const openDay=(value:string)=>{dayOpener.current=document.activeElement instanceof HTMLElement?document.activeElement:document.querySelector<HTMLElement>('[role="tab"][data-state="active"]');setSelectedDay(value);};
  return <div className="mx-auto w-full max-w-[1320px] space-y-5 pb-10">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
      <div className="min-w-0"><h1 ref={heading} tabIndex={-1} className="rounded-sm text-2xl font-semibold tracking-tight focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring sm:text-3xl">{currentPerson?currentPerson.name:'Uso, resultados y créditos'}</h1>
        <p className="mt-1 text-sm leading-6 text-muted-foreground">{currentPerson?'Actividad, avance comercial y consumo de esta persona.':'Quién usa ANTON.IA, qué está consiguiendo y qué conviene revisar.'}</p>
        {person&&<Button variant="ghost" size="sm" className="mt-2 -ml-2" onClick={()=>{setPerson('');setView('people');}}><ArrowLeft aria-hidden="true"/>Volver al equipo</Button>}</div>
      <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={exportCsv} disabled={!data||loading||!data.ready}><Download aria-hidden="true"/>Exportar resumen</Button><Button variant="ghost" onClick={()=>void load()} disabled={loading}><RefreshCw className={cn(loading&&'animate-spin motion-reduce:animate-none')} aria-hidden="true"/>{loading?'Actualizando':'Actualizar'}</Button></div>
    </header>
    <section className="rounded-2xl border border-border/60 bg-card p-4" aria-label="Período y alcance del informe">
      <div className="mb-3 flex flex-wrap gap-1.5">{[['Hoy',1],['Ayer',0],['7 días',7],['30 días',30],['90 días',90]].map(([label,days])=><Button key={label} variant="ghost" size="sm" onClick={()=>shortcuts(Number(days))}>{label}</Button>)}</div>
      <div className={cn('grid gap-3 sm:grid-cols-2',data?.platform?'xl:grid-cols-4':'xl:grid-cols-3')}>
        {data?.platform&&<div className="space-y-1.5"><Label htmlFor="usage-company">Empresa</Label><Select value={org||'all'} onValueChange={value=>{setOrg(value);setGroup('');setPerson('');}}><SelectTrigger id="usage-company"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Toda ANTON.IA</SelectItem>{data.organizations.map(o=><SelectItem key={o.id} value={o.id}>{o.name}</SelectItem>)}</SelectContent></Select></div>}
        <div className="space-y-1.5"><Label htmlFor="usage-team">Equipo</Label><Select value={group||'all'} onValueChange={value=>{setGroup(value==='all'?'':value);setPerson('');}}><SelectTrigger id="usage-team"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos los equipos</SelectItem>{data?.groups.filter(g=>org==='all'||!org||g.organizationId===org).map(g=><SelectItem key={g.id} value={g.id}>{g.name}</SelectItem>)}</SelectContent></Select></div>
        <div className="space-y-1.5"><Label htmlFor="usage-from">Desde</Label><Input id="usage-from" type="date" value={from} max={to} onChange={event=>setFrom(event.target.value)}/></div>
        <div className="space-y-1.5"><Label htmlFor="usage-to">Hasta</Label><Input id="usage-to" type="date" value={to} min={from} max={dayInZone(new Date())} onChange={event=>setTo(event.target.value)}/></div>
      </div>
      {data&&!data.platform&&<p className="mt-3 text-xs text-muted-foreground">{data.organizations.find(o=>o.id===effectiveOrg)?.name||'Tu organización'} · Los filtros se aplican al informe completo.</p>}
    </section>
    {error&&<div role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm"><p>{error}</p><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={()=>void load()}>Reintentar</Button><Button variant="ghost" size="sm" onClick={()=>{setOrg('');setGroup('');setPerson('');}}>Restablecer alcance</Button></div></div>}
    {exportError&&<p role="alert" className="text-sm text-destructive">{exportError}</p>}
    {loading&&!data&&<Loading/>}
    {data&&!data.ready&&<Card><CardContent className="p-6"><h2 className="font-semibold">Estamos preparando la medición</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">El informe todavía no tiene todas sus fuentes disponibles. Conservamos el equipo seleccionado y no presentamos la ausencia de datos como cero actividad.</p><Button variant="outline" className="mt-4" onClick={()=>void load()}>Actualizar informe</Button></CardContent></Card>}
    {data?.ready&&<div className="space-y-5" aria-busy={loading}>
      {data.coverage.unavailable.length>0&&<div role="status" className="flex gap-3 rounded-xl border border-border bg-muted/40 p-4 text-sm"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" aria-hidden="true"/><p className="leading-6">Parte del histórico es anterior a la medición de navegación o clasificación de respuestas. Mostramos el trabajo registrado; los datos incompletos aparecen como «—». {data.coverage.captureFrom&&`La navegación se registra desde ${time(data.coverage.captureFrom)}.`}</p></div>}
      <div className="grid grid-cols-2 gap-3 xl:grid-cols-4">
        <Metric label="Personas activas" value={data.summary.active} detail={`de ${n(data.summary.people)} · uso humano registrado`} icon={Users}/>
        <Metric label="Interés registrado" value={data.summary.commercial.interested} detail="Contactos con respuesta positiva o solicitud de reunión" icon={CheckCircle2}/>
        <Metric label="Reuniones registradas" value={data.summary.commercial.meetingRegistered} detail="Compromisos de reunión con fecha" icon={CalendarDays}/>
        <Metric label="Créditos de la app" value={data.summary.credits} detail="Consumo neto del período, sin duplicar cupos" icon={Coins}/>
      </div>
      <Tabs value={view} onValueChange={setView}>
        <TabsList className="mb-4 grid h-auto w-full grid-cols-2 gap-1 sm:w-auto sm:inline-flex"><TabsTrigger value="summary">Resumen</TabsTrigger><TabsTrigger value="people">Personas</TabsTrigger><TabsTrigger value="commercial">Comercial</TabsTrigger><TabsTrigger value="history">Histórico diario</TabsTrigger></TabsList>
        <TabsContent value="summary" className="space-y-5">
          <div className="grid gap-5 xl:grid-cols-[minmax(0,1.3fr)_minmax(300px,1fr)]">
            <Card><CardHeader className="flex flex-row flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-base">Cuándo se utiliza</CardTitle><p className="mt-1 text-xs text-muted-foreground">Selecciona un día para ver su resumen.</p></div><div className="flex gap-1"><Button size="sm" variant={chart==='active'?'secondary':'ghost'} onClick={()=>setChart('active')}>Personas</Button><Button size="sm" variant={chart==='credits'?'secondary':'ghost'} onClick={()=>setChart('credits')}>Créditos</Button></div></CardHeader>
              <CardContent className="px-2 sm:px-4"><ChartContainer config={chartConfig} className="h-64 w-full aspect-auto"><AreaChart accessibilityLayer data={data.daily} margin={{left:-12,right:8,top:8,bottom:0}} onClick={event=>{if(event?.activeLabel)openDay(String(event.activeLabel));}}><CartesianGrid vertical={false}/><XAxis dataKey="day" tickFormatter={date} tickLine={false} axisLine={false} minTickGap={25}/><YAxis allowDecimals={false} tickLine={false} axisLine={false}/><Tooltip content={<ChartTooltipContent labelFormatter={value=>date(String(value))}/>}/><Area isAnimationActive={false} dataKey={chart} type="monotone" stroke={`var(--color-${chart})`} fill={`var(--color-${chart})`} fillOpacity={.14} strokeWidth={2}/></AreaChart></ChartContainer>
                <p className="px-3 text-xs leading-5 text-muted-foreground">{chart==='active'?'Días y horas de actividad en Chile.':'Los créditos corresponden al día del cupo UTC; el saldo de hoy respeta su reinicio diario.'}</p></CardContent></Card>
            <Card><CardHeader><CardTitle className="text-base">Para qué la utilizan</CardTitle><p className="text-xs leading-5 text-muted-foreground">Visitas humanas y trabajo registrado, medidos por separado.</p></CardHeader><CardContent className="space-y-4">{data.modules.filter(m=>m.users||m.operations||m.visits).slice(0,8).map(m=><div key={m.id}><div className="flex justify-between gap-3 text-sm"><span>{m.label}</span><span className="shrink-0 tabular-nums text-muted-foreground">{n(m.users)} personas</span></div><div className="mt-1.5 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-primary/70" style={{width:`${Math.max(m.users?3:0,data.summary.active?m.users/data.summary.active*100:0)}%`}}/></div><p className="mt-1 text-xs text-muted-foreground">{n(m.visits)} visitas · {n(m.operations)} operaciones registradas</p></div>)}{!data.modules.some(m=>m.users||m.operations||m.visits)&&<p className="text-sm text-muted-foreground">Sin uso registrado en este período. Prueba otro rango.</p>}</CardContent></Card>
          </div>
          <Card><CardHeader><CardTitle className="text-base">Qué necesita atención</CardTitle><p className="text-xs text-muted-foreground">Pendientes actuales y señales del período. Cada señal incluye su evidencia.</p></CardHeader><CardContent className="divide-y divide-border">{data.diagnostics.slice(0,10).map(d=><div key={d.id} className="flex flex-col gap-3 py-4 first:pt-0 sm:flex-row sm:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{diagnosticLabels[d.category]}</Badge><h3 className="text-sm font-semibold">{d.title}</h3><span className="text-sm font-semibold tabular-nums">{n(d.count)}</span></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{d.detail}</p>{d.userId&&<p className="mt-1 text-xs text-muted-foreground">{data.people.find(p=>p.id===d.userId&&p.organizationId===d.organizationId)?.name||'Responsable registrado'}</p>}</div>{d.userId&&d.organizationId?<Button size="sm" variant="outline" onClick={()=>openPerson(d.organizationId!,d.userId!)}>Ver persona<ChevronRight aria-hidden="true"/></Button>:<Button size="sm" variant="ghost" onClick={()=>setView(d.category==='observing'||d.category==='strategy'?'commercial':'people')}>Revisar<ArrowRight aria-hidden="true"/></Button>}</div>)}{data.diagnostics.length===0&&<div className="flex items-start gap-3 rounded-xl bg-muted/30 p-4"><CheckCircle2 className="h-5 w-5 shrink-0 text-primary" aria-hidden="true"/><div><p className="text-sm font-medium">Sin bloqueos registrados</p><p className="mt-1 text-sm text-muted-foreground">Revisa el recorrido comercial para valorar el avance y la cobertura de resultados.</p></div></div>}</CardContent></Card>
        </TabsContent>
        <TabsContent value="people" className="space-y-4">
          <div className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-[minmax(0,1fr)_220px]"><div className="space-y-1.5"><Label htmlFor="usage-search">Buscar persona</Label><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" aria-hidden="true"/><Input id="usage-search" type="search" className="pl-9" placeholder="Nombre o correo" value={query} onChange={event=>setQuery(event.target.value)}/></div></div><div className="space-y-1.5"><Label htmlFor="usage-sort">Ordenar por</Label><Select value={sort} onValueChange={setSort}><SelectTrigger id="usage-sort"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="activity">Actividad reciente</SelectItem><SelectItem value="days">Días con uso</SelectItem><SelectItem value="credits">Créditos atribuidos</SelectItem><SelectItem value="pending">Pendientes</SelectItem></SelectContent></Select></div></div>
          <Card className="overflow-hidden"><Table><TableHeader><TableRow><TableHead>Persona</TableHead><TableHead className="hidden md:table-cell">Último uso</TableHead><TableHead className="text-right">Días</TableHead><TableHead className="hidden lg:table-cell">Funciones</TableHead><TableHead className="text-right">Créditos</TableHead><TableHead className="hidden sm:table-cell text-right">Interés</TableHead><TableHead className="hidden sm:table-cell text-right">Pendientes</TableHead><TableHead><span className="sr-only">Abrir persona</span></TableHead></TableRow></TableHeader><TableBody>{visiblePeople.map(p=><TableRow key={`${p.organizationId}:${p.id}`}><TableCell className="max-w-[220px]"><button onClick={()=>openPerson(p.organizationId,p.id)} className="block rounded-sm text-left text-sm font-semibold hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{p.name}</button><p className="max-w-[180px] truncate text-xs text-muted-foreground">{p.email||(!p.member?'Actividad histórica':'')}</p>{data.platform&&<p className="max-w-[180px] truncate text-xs text-muted-foreground">{data.organizations.find(o=>o.id===p.organizationId)?.name}</p>}</TableCell><TableCell className="hidden md:table-cell text-xs text-muted-foreground">{time(p.lastAt)}</TableCell><TableCell className="text-right tabular-nums">{n(p.activeDays)}</TableCell><TableCell className="hidden lg:table-cell max-w-[220px] text-xs text-muted-foreground">{p.modules.map(m=>USAGE_MODULES[m]).join(' · ')||'Sin visita registrada'}</TableCell><TableCell className="text-right tabular-nums">{n(p.credits)}</TableCell><TableCell className="hidden sm:table-cell text-right tabular-nums">{n(p.commercial.interested)}</TableCell><TableCell className="hidden sm:table-cell text-right tabular-nums">{n(p.pending)}</TableCell><TableCell><Button variant="ghost" size="icon" aria-label={`Ver uso de ${p.name}`} onClick={()=>openPerson(p.organizationId,p.id)}><ChevronRight aria-hidden="true"/></Button></TableCell></TableRow>)}</TableBody></Table>{visiblePeople.length===0&&<div className="p-8 text-center"><h2 className="font-medium">No encontramos personas</h2><p className="mt-1 text-sm text-muted-foreground">Prueba otro nombre o amplía el alcance.</p><Button variant="outline" size="sm" className="mt-4" onClick={()=>{setQuery('');setGroup('');}}>Limpiar filtros</Button></div>}</Card>
          <p className="text-xs leading-5 text-muted-foreground">«—» indica consumo sin atribución individual suficiente. Una operación automática no cuenta como día de uso humano.</p>
        </TabsContent>
        <TabsContent value="commercial" className="space-y-5">
          <Card><CardHeader><CardTitle className="text-base">Recorrido comercial</CardTitle><p className="text-sm leading-6 text-muted-foreground">Hechos registrados en el período. Las etapas son entradas observadas, no conversiones inferidas por la posición actual.</p></CardHeader><CardContent><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{commercialLabels.map(item=><div key={item.key} className="flex items-center justify-between gap-3 rounded-xl border border-border/60 px-4 py-3"><span className="text-sm">{item.label}</span><strong className="shrink-0 text-lg tabular-nums">{n(data.summary.commercial[item.key])}</strong></div>)}</div><p className="mt-4 text-xs leading-5 text-muted-foreground">Una solicitud de reunión no es una reunión registrada, y marcar un cierre en CRM no verifica una compra externa. Las reuniones realizadas son las marcadas expresamente como completadas.</p></CardContent></Card>
          <Card><CardHeader className="flex flex-row flex-wrap items-start justify-between gap-4"><div><CardTitle className="text-base">Conversión de correo</CardTitle><p className="mt-1 text-sm text-muted-foreground">Los mismos contactos, con el mismo tiempo para responder.</p></div><div className="w-48 space-y-1.5"><Label htmlFor="usage-horizon">Tiempo de observación</Label><Select value={horizon} onValueChange={setHorizon}><SelectTrigger id="usage-horizon"><SelectValue/></SelectTrigger><SelectContent>{[7,14,30,60].map(days=><SelectItem key={days} value={String(days)}>{days} días</SelectItem>)}</SelectContent></Select></div></CardHeader><CardContent>
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[{label:'Contactos del grupo',value:n(data.conversion.contacted)},{label:'Con ventana completa',value:n(data.conversion.mature)},{label:'Respuesta humana',value:data.conversion.replyRate===null?'—':n(data.conversion.replyRate)+' %'},{label:'Interés',value:data.conversion.interestRate===null?'—':n(data.conversion.interestRate)+' %'}].map(item=><div key={item.label} className="rounded-xl bg-muted/30 p-4"><p className="text-xs text-muted-foreground">{item.label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{item.value}</p></div>)}</div>
            <p className="mt-4 text-sm leading-6 text-muted-foreground">{n(data.conversion.observing)} contactos siguen en observación · {n(data.conversion.unknown)} con información incompleta. Las respuestas automáticas y rebotes se excluyen de la respuesta humana.</p>
            <p className="mt-2 text-xs leading-5 text-muted-foreground">Período anterior comparable: {n(data.previousConversion.mature)} contactos con ventana completa · tasa de respuesta {data.previousConversion.replyRate===null?'no disponible':n(data.previousConversion.replyRate)+' %'}. La clasificación antigua o una sincronización incompleta impiden afirmar una tasa.</p>
          </CardContent></Card>
          <Card><CardHeader><CardTitle className="text-base">En qué se consumen los créditos</CardTitle></CardHeader><CardContent className="space-y-3">{data.creditResources.map(c=><div key={c.resource} className="flex justify-between gap-3 border-b border-border/60 pb-3 last:border-0"><span className="text-sm">{{search:'Búsqueda',enrich:'Completar datos',investigate:'Investigación y datos avanzados'}[c.resource]}</span><strong className="tabular-nums">{n(c.net)}</strong></div>)}<p className="text-xs leading-5 text-muted-foreground">{n(data.coverage.unassignedCredits)} créditos sin reparto individual o empresa suficiente. El consumo de una función puede ser cero aunque se utilice; el conteo conserva las reglas de la app.</p></CardContent></Card>
        </TabsContent>
        <TabsContent value="history" className="space-y-4">
          <div><h2 className="text-lg font-semibold">Histórico por día</h2><p className="mt-1 text-sm text-muted-foreground">Selecciona un día para entender su actividad y resultados juntos.</p></div>
          <div className="max-h-[36rem] space-y-2 overflow-y-auto rounded-2xl border border-border/60 bg-card p-3" role="region" aria-label="Resúmenes diarios" tabIndex={0}>{[...data.daily].reverse().map(d=><button key={d.day} onClick={()=>openDay(d.day)} className="flex w-full flex-col gap-2 rounded-xl border border-border/50 px-4 py-3 text-left transition-colors hover:bg-muted/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring sm:flex-row sm:items-center sm:justify-between"><span><span className="flex items-center gap-2 text-sm font-semibold"><CalendarDays className="h-4 w-4 text-muted-foreground" aria-hidden="true"/>{date(d.day)}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{d.modules.length?d.modules.map(m=>USAGE_MODULES[m]).join(' · '):'Sin visitas humanas registradas'}{d.firstAt&&` · ${time(d.firstAt)} a ${time(d.lastAt)}`}</span></span><span className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-muted-foreground"><span><strong className="text-foreground tabular-nums">{n(d.active)}</strong> personas</span><span><strong className="text-foreground tabular-nums">{n(d.commercial.contacted)}</strong> contactados</span><span><strong className="text-foreground tabular-nums">{n(d.credits)}</strong> créditos del cupo</span><ChevronRight className="h-4 w-4" aria-hidden="true"/></span></button>)}</div>
        </TabsContent>
      </Tabs>
      {person&&<Card><CardHeader><CardTitle className="text-base">Cupo disponible hoy</CardTitle></CardHeader><CardContent>{data.limits.find(l=>l?.userId===person&&l.organizationId===org)?(()=>{const limit=data.limits.find(l=>l?.userId===person&&l.organizationId===org)!;return <p className="text-sm leading-6">{n(limit!.used)} de {n(limit!.limit)} usados · {n(limit!.remaining)} disponibles · {limit!.binding==='team'?'cupo compartido del equipo':'cupo individual'}.</p>;})():<p className="text-sm text-muted-foreground">No pudimos comprobar el cupo actual. El consumo histórico se conserva.</p>}<Button asChild variant="link" className="mt-2 -ml-4"><Link href="/dashboard/admin/credits">Ver límites de mi organización</Link></Button></CardContent></Card>}
      <footer className="flex flex-col gap-2 border-t border-border/60 pt-4 text-xs leading-5 text-muted-foreground sm:flex-row sm:justify-between"><span>Actualizado: {time(data.generatedAt)} · actividad en hora de Chile</span><span>Consumo según el cupo diario UTC · pendientes actuales</span></footer>
    </div>}
    <Sheet open={Boolean(selectedDay)} onOpenChange={open=>{if(!open)setSelectedDay(null);}}>
      <SheetContent onCloseAutoFocus={event=>{event.preventDefault();if(dayOpener.current?.isConnected)dayOpener.current.focus();}}
        className="w-full overflow-y-auto sm:max-w-lg [&>button]:flex [&>button]:h-11 [&>button]:w-11 [&>button]:items-center [&>button]:justify-center">
        <SheetHeader><SheetTitle>{selectedDay?date(selectedDay):'Resumen diario'}</SheetTitle><SheetDescription>Actividad humana, trabajo registrado y consumo del cupo diario.</SheetDescription></SheetHeader>
        {day&&<div className="mt-6 space-y-5">
          <p className="text-sm leading-6">{n(day.active)} personas con uso humano registrado{day.modules.length?` en ${day.modules.map(m=>USAGE_MODULES[m]).join(', ')}`:''}.</p>
          <div className="rounded-xl border p-4"><p className="text-sm font-semibold">{n(day.credits)} créditos del cupo de este día</p><p className="mt-1 text-xs leading-5 text-muted-foreground">El cupo usa días UTC; las visitas y resultados comerciales de abajo usan hora de Chile.</p></div>
          <dl className="space-y-3">{commercialLabels.filter(item=>day.commercial[item.key]>0).map(item=><div key={item.key} className="flex justify-between gap-3 border-b pb-2"><dt className="text-sm text-muted-foreground">{item.label}</dt><dd className="font-semibold tabular-nums">{n(day.commercial[item.key])}</dd></div>)}</dl>
          <section className="space-y-3"><h3 className="text-sm font-semibold">Quiénes participaron</h3>{day.people.map(p=><div key={`${p.organizationId}:${p.id}`} className="rounded-xl border p-3"><button onClick={()=>{setSelectedDay(null);openPerson(p.organizationId,p.id);}} className="rounded-sm text-sm font-semibold hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{p.name}</button><p className="mt-1 text-xs leading-5 text-muted-foreground">{p.active?p.modules.map(m=>USAGE_MODULES[m]).join(' · '):'Trabajo asociado, sin visita humana registrada'} · {n(p.commercial.contacted)} contactados · {n(p.commercial.interested)} con interés</p></div>)}{day.people.length===0&&<p className="text-sm text-muted-foreground">No hay personas atribuibles para este día.</p>}</section>
          {day.actions===0&&<p className="text-sm text-muted-foreground">Sin operaciones registradas en este día. Las visitas, si existen, se muestran por separado.</p>}
        </div>}
      </SheetContent>
    </Sheet>
  </div>;
}
