/**
 * The select options of Apify «Leads Finder» (code_crafter/leads-finder) that the mapper may send, copied from the
 * actor's published input schema (build 0.0.56, 5 Oct 2026; GET /v2/acts/code_crafter~leads-finder/builds/default).
 * contact_location keeps the countries and the Chilean regions out of its 1,857 options.
 */
export const LEADS_FINDER_ENUMS = {
  seniority_level: [
    "founder",
    "owner",
    "c_suite",
    "director",
    "partner",
    "vp",
    "head",
    "manager",
    "senior",
    "entry",
    "trainee",
  ],
  email_status: [
    "validated",
    "not_validated",
    "unknown",
  ],
  size: [
    "1-10",
    "11-20",
    "21-50",
    "51-100",
    "101-200",
    "201-500",
    "501-1000",
    "1001-2000",
    "2001-5000",
    "5001-10000",
    "10001-20000",
    "20001-50000",
    "50000+",
  ],
  company_industry: [
    "information technology & services",
    "construction",
    "marketing & advertising",
    "real estate",
    "health, wellness & fitness",
    "management consulting",
    "computer software",
    "internet",
    "retail",
    "financial services",
    "consumer services",
    "hospital & health care",
    "automotive",
    "restaurants",
    "education management",
    "food & beverages",
    "design",
    "hospitality",
    "accounting",
    "events services",
    "nonprofit organization management",
    "entertainment",
    "electrical/electronic manufacturing",
    "leisure, travel & tourism",
    "professional training & coaching",
    "transportation/trucking/railroad",
    "law practice",
    "apparel & fashion",
    "architecture & planning",
    "mechanical or industrial engineering",
    "insurance",
    "telecommunications",
    "human resources",
    "staffing & recruiting",
    "sports",
    "legal services",
    "oil & energy",
    "media production",
    "machinery",
    "wholesale",
    "consumer goods",
    "music",
    "photography",
    "medical practice",
    "cosmetics",
    "environmental services",
    "graphic design",
    "business supplies & equipment",
    "renewables & environment",
    "facilities services",
    "publishing",
    "food production",
    "arts & crafts",
    "building materials",
    "civil engineering",
    "religious institutions",
    "public relations & communications",
    "higher education",
    "printing",
    "furniture",
    "mining & metals",
    "logistics & supply chain",
    "research",
    "pharmaceuticals",
    "individual & family services",
    "medical devices",
    "civic & social organization",
    "e-learning",
    "security & investigations",
    "chemicals",
    "government administration",
    "online media",
    "investment management",
    "farming",
    "writing & editing",
    "textiles",
    "mental health care",
    "primary/secondary education",
    "broadcast media",
    "biotechnology",
    "information services",
    "international trade & development",
    "motion pictures & film",
    "consumer electronics",
    "banking",
    "import & export",
    "industrial automation",
    "recreational facilities & services",
    "performing arts",
    "utilities",
    "sporting goods",
    "fine art",
    "airlines/aviation",
    "computer & network security",
    "maritime",
    "luxury goods & jewelry",
    "veterinary",
    "venture capital & private equity",
    "wine & spirits",
    "plastics",
    "aviation & aerospace",
    "commercial real estate",
    "computer games",
    "packaging & containers",
    "executive office",
    "computer hardware",
    "computer networking",
    "market research",
    "outsourcing/offshoring",
    "program development",
    "translation & localization",
    "philanthropy",
    "public safety",
    "alternative medicine",
    "museums & institutions",
    "warehousing",
    "defense & space",
    "newspapers",
    "paper & forest products",
    "law enforcement",
    "investment banking",
    "government relations",
    "fund-raising",
    "think tanks",
    "glass, ceramics & concrete",
    "capital markets",
    "semiconductors",
    "animation",
    "political organization",
    "package/freight delivery",
    "wireless",
    "international affairs",
    "public policy",
    "libraries",
    "gambling & casinos",
    "railroad manufacture",
    "ranching",
    "military",
    "fishery",
    "supermarkets",
    "dairy",
    "tobacco",
    "shipbuilding",
    "judiciary",
    "alternative dispute resolution",
    "nanotechnology",
    "agriculture",
    "legislative office",
  ],
  contact_location_sample: [
    "united states",
    "germany",
    "india",
    "united kingdom",
    "russia",
    "france",
    "china",
    "canada",
    "netherlands",
    "mexico",
    "belgium",
    "japan",
    "brazil",
    "australia",
    "poland",
    "thailand",
    "sweden",
    "portugal",
    "spain",
    "czech republic",
    "taiwan",
    "south africa",
    "colombia",
    "italy",
    "vietnam",
    "nigeria",
    "singapore",
    "hong kong",
    "ireland",
    "israel",
    "switzerland",
    "turkey",
    "romania",
    "south korea",
    "indonesia",
    "united arab emirates",
    "saudi arabia",
    "austria",
    "philippines",
    "peru",
    "malaysia",
    "argentina",
    "ukraine",
    "ghana",
    "denmark",
    "norway",
    "finland",
    "puerto rico",
    "qatar",
    "macau",
    "new zealand",
    "hungary",
    "luxembourg",
    "kuwait",
    "egypt",
    "slovakia",
    "greece",
    "kenya",
    "bulgaria",
    "costa rica",
    "chile",
    "venezuela",
    "afghanistan",
    "bangladesh",
    "malta",
    "guatemala",
    "pakistan",
    "lithuania",
    "panama",
    "morocco",
    "republic of indonesia",
    "uruguay",
    "serbia",
    "bolivia",
    "angola",
    "dominican republic",
    "ecuador",
    "oman",
    "jamaica",
    "zambia",
    "lebanon",
    "tanzania",
    "jordan",
    "algeria",
    "gibraltar",
    "paraguay",
    "cambodia",
    "uganda",
    "mozambique",
    "ethiopia",
    "belarus",
    "republic of the union of myanmar",
    "croatia",
    "jersey",
    "iraq",
    "isle of man",
    "el salvador",
    "estonia",
    "latvia",
    "côte d'ivoire",
    "tunisia",
    "sierra leone",
    "senegal",
    "sri lanka",
    "cyprus",
    "kazakhstan",
    "guernsey",
    "bermuda",
    "mali",
    "honduras",
    "bahrain",
    "slovenia",
    "papua new guinea",
    "iceland",
    "mauritius",
    "iran",
    "niger",
    "rwanda",
    "moldova",
    "democratic republic of the congo",
    "liechtenstein",
    "fiji",
    "kyrgyzstan",
    "azerbaijan",
    "madagascar",
    "trinidad and tobago",
    "lesotho",
    "nicaragua",
    "cameroon",
    "barbados",
    "armenia",
    "haiti",
    "maldives",
    "guam",
    "laos",
    "nepal",
    "brunei",
    "reunion",
    "macedonia (fyrom)",
    "swaziland",
    "liberia",
    "uzbekistan",
    "sudan",
    "anguilla",
    "cuba",
    "cayman islands",
    "seychelles",
    "saint kitts and nevis",
    "suriname",
    "bosnia and herzegovina",
    "malawi",
    "the bahamas",
    "botswana",
    "syria",
    "burundi",
    "guadeloupe",
    "namibia",
    "burkina faso",
    "somalia",
    "greenland",
    "equatorial guinea",
    "chad",
    "monaco",
    "republic of the congo",
    "u.s. virgin islands",
    "mayotte",
    "french polynesia",
    "french guiana",
    "andorra",
    "new caledonia",
    "central african republic",
    "myanmar (burma)",
    "belize",
    "aland islands",
    "solomon islands",
    "kosovo",
    "gabon",
    "benin",
    "martinique",
    "tonga",
    "south sudan",
    "cook islands",
    "georgia",
    "mauritania",
    "turkmenistan",
    "libya",
    "falkland islands (islas malvinas)",
    "bhutan",
    "tajikistan",
    "northern mariana islands",
    "western sahara",
    "guyana",
    "dominica",
    "vanuatu",
    "kiribati",
    "togo",
    "nauru",
    "samoa",
    "mongolia",
    "myanmar",
    "yemen",
    "albania",
    "montenegro",
    "santiago metropolitan region, chile",
    "antofagasta region, chile",
    "bío bío region, chile",
    "valparaiso region, chile",
    "los ríos region, chile",
    "magallanes y la antártica chilena region, chile",
    "los lagos region, chile",
    "bio-bio, chile",
    "coquimbo region, chile",
  ],
} as const satisfies Record<string, readonly string[]>;
