// Synthetic approval/evidence fixtures, not verified GrupoExpro marketing claims.
// The user's template document supplies service categories and writing patterns only.
export const draftQualityFixtures = [
  { service: 'Servicios transitorios', role: 'Gerente de Operaciones', fact: 'Acme publica vacantes de personal para su temporada.', capability: 'Contratacion de personal transitorio', offer: 'En GrupoExpro contratamos personal transitorio para apoyar la dotacion de temporada con un alcance definido junto al equipo.', previous: 'El tema anterior fue la dotacion de temporada.' },
  { service: 'Outsourcing / BPO', role: 'Gerente de Logistica', fact: 'Acme opera una bodega de distribucion.', capability: 'Supervision de procesos de bodega', offer: 'En GrupoExpro supervisamos procesos de bodega para que el equipo concentre la gestion operativa en un servicio de alcance acordado.', previous: 'El tema anterior fue la supervision de bodega.' },
  { service: 'Seleccion y Hunting', role: 'Gerente de Personas', fact: 'Acme publica una vacante de jefatura.', capability: 'Seleccion y evaluacion de candidatos', offer: 'En GrupoExpro evaluamos candidatos para apoyar la seleccion de la jefatura con antecedentes pertinentes al perfil publicado por Acme.', previous: 'El tema anterior fue la evaluacion de candidatos.' },
  { service: 'ExproFacility', role: 'Jefe de Servicios Generales', fact: 'Acme opera instalaciones regionales.', capability: 'Servicios de aseo de instalaciones', offer: 'En GrupoExpro prestamos servicios de aseo para apoyar el cuidado de las instalaciones con un alcance acordado con su equipo.', previous: 'El tema anterior fue el alcance del aseo.' },
  { service: 'ExproSecurity', role: 'Jefe de Seguridad', fact: 'Acme opera un recinto industrial.', capability: 'Vigilancia de recintos', offer: 'En GrupoExpro cubrimos vigilancia de recintos para apoyar el resguardo del recinto industrial con un servicio de alcance acordado.', previous: 'El tema anterior fue el alcance de vigilancia.' },
  { service: 'GrupoExpro Technology', role: 'Gerente de Administracion', fact: 'Acme publica procesos de gestion de personas.', capability: 'Plataformas de gestion de personas', offer: 'En GrupoExpro implementamos plataformas de gestion de personas para que el equipo consulte los registros de sus procesos en un mismo lugar.', previous: 'El tema anterior fue la consulta de registros.' },
] as const;
